import {mountScene,esc} from './render.js';
const $=s=>document.querySelector(s);
let data,source,demo,current,view,seconds=0,progress=0,playing=true,annotations=false,raf=0,last=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');$('#motion').checked=reduced.matches;
const status=s=>({source_text:'원문',shared_merged_source:'병합 원문 공유',proposed_copy:'시연용 제안',proposed_split_of_merged_source:'병합 V.O 분할 제안',missing_in_source:'원문 미기입'}[s]||s);
const duration=()=>current.duration.sourceSeconds??current.duration.previewSeconds;
function tell(s){$('#message').textContent=s;clearTimeout(tell.timer);tell.timer=setTimeout(()=>$('#message').textContent='',3000)}
function stopClock(){cancelAnimationFrame(raf);raf=0;last=0}
function startClock(){stopClock();if(playing&&!document.hidden&&!$('#motion').checked)raf=requestAnimationFrame(tick)}
function tick(now){if(!last)last=now;const delta=Math.min((now-last)/1000,.1);last=now;if(playing&&!document.hidden){seconds+=delta;if($('#mode').value==='sequence'){progress=Math.min(1,progress+delta/duration());if(progress===1){playing=false;syncControls()}}draw();if(playing)raf=requestAnimationFrame(tick)}}
function draw(){view?.update($('#mode').value==='sequence'?progress*demo.cuts[current.id].loopSeconds:seconds,{reduced:$('#motion').checked,mode:$('#mode').value,progress});const p=$('#mode').value==='always'?(seconds%demo.cuts[current.id].loopSeconds)/demo.cuts[current.id].loopSeconds:progress;$('#seek').value=Math.round(p*1000);$('#time').textContent=$('#mode').value==='always'?`${(p*demo.cuts[current.id].loopSeconds).toFixed(1)} / ${demo.cuts[current.id].loopSeconds}초 반복`:`${(progress*duration()).toFixed(1)} / ${duration()}초`;$('#cues').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===(p<.35?0:p<.7?1:2)))}
function syncControls(){$('#play').textContent=playing?'Ⅱ 동작 멈춤':'▶ 동작 재개';$('#loop-status').textContent=$('#motion').checked?'정보를 갖춘 정적 상태':$('#mode').value==='always'?'현재 컷 안에서 반복':'컷별 연출 순서';}
function go(c){if(c)location.hash=`scenario=${c.scenario}&cut=${c.cut}`}
function move(n){const a=data.cuts.filter(c=>c.scenario===current.scenario);go(a[a.indexOf(current)+n])}
function details(){const v=demo.cuts[current.id],raw=source.cuts.find(c=>c.id===current.id);$('#spec').innerHTML=`<p>표시용 문구는 이번 요청의 시연 카피입니다. 원문 셀·V.O·컷 번호는 별도로 보존합니다. 좌표와 루프 연출은 구현 시안입니다.</p><div class="source-grid"><section><h3>화면용 카피 · 시연용 제안</h3>${v.displayCopy.map(t=>`<p>${esc(t)}</p>`).join('')}</section><section><h3>주석 번호 / 화면 영역</h3>${view.captions.map(p=>`<p>${String(p.index).padStart(2,'0')} · ${esc(p.title)}<br><code>${esc(p.bounds)}</code><br>${esc(p.copy)}</p>`).join('')}</section></div><h3>배치 설계 참고 · 실제 화면은 위 영역별 명세 우선</h3><table><thead><tr><th>종류</th><th>원문·제안 구분</th><th>원래 좌표 / 노트</th></tr></thead><tbody>${current.elements.map(e=>`<tr><td>${e.kind==='rendered_region'?'화면 영역':esc(e.kind)}</td><td>${e.text.map(t=>`${esc(t.value)} 〔${esc(status(t.status))} · ${esc(t.sourceCell||'패키지 제안')}〕`).join('<br>')}</td><td>${e.boundsPct.join(', ')}<br>${esc(e.note)}</td></tr>`).join('')}</tbody></table>`;
$('#source').innerHTML=`<p><a href="${esc(current.source.url)}" target="_blank" rel="noopener">최신 스토리보드 · ${esc(current.source.sheet)} · ${current.source.row}행</a></p><div class="source-grid"><section><h3>화면 구성 · ${esc(current.source.screenCell)}</h3><pre>${esc(current.sourceScreenText)}</pre><h3>필요 에셋 · ${esc(current.source.assetCell)}</h3><pre>${esc(current.sourceAssetText||'원문 미기입')}</pre><h3>V.O 원문 · ${esc(current.vo.sourceRange)}</h3><pre>${esc(current.sourceVoText||'원문 미기입')}</pre><h3>UI 원문 · ${esc(current.source.uiCell)}</h3><pre>${esc(current.sourceUiText||'이 행 원문 미기입')}</pre><h3>UI 병합 범위 · ${esc(current.sourceUiRange)}</h3><pre>${esc(current.sourceUiMergedText||'원문 미기입')}</pre><h3>참고 대본 J열 · ${esc(current.referenceScript.range)} · V.O 대체에 사용하지 않음</h3><pre>${esc(current.referenceScript.text||'원문 미기입')}</pre></section><section><h3>원 제작노트 · 미정 사항</h3><pre>${esc([...current.productionNotes,...current.issues].join('\n'))}</pre>${current.scenario===4&&current.scene>=4?`<h3>이번 시연안의 상태 편집</h3><p>${esc(demo.editorialNote)}</p>`:''}<h3>메모·댓글 — 본문과 별도</h3>${current.sourceComments.map(s=>`<h4>${esc(s.cell)} · ${s.kind==='note'?'메모':esc(s.kind)}</h4><pre>${esc(s.text)}</pre>`).join('')||'<p>관련 메모·댓글 없음</p>'}</section></div><div class="references">${current.referenceImages.map(r=>`<figure><a href="./${esc(r.path)}" target="_blank" rel="noopener"><img src="./${esc(r.path)}" alt="${esc(current.id)} 원문 화면 예시" loading="lazy"></a><figcaption>${esc(r.sourceAnchor)} · 원문 화면 예시</figcaption></figure>`).join('')||'<p>원 패키지의 화면 예시 없음</p>'}</div><details><summary>추출 셀 전체</summary><div class="source-grid">${Object.entries(raw.cells).map(([k,v])=>`<section><h3>${esc(k)}</h3><pre>${esc(v)}</pre></section>`).join('')}</div></details>`;}
function load(){stopClock();const p=new URLSearchParams(location.hash.slice(1));const legacy=p.get('scenario')==='2'&&p.get('cut')==='3.5';if(legacy)p.set('cut','3.2');$('#compat-notice').hidden=!legacy;$('#compat-notice').textContent=legacy?'이전 버전의 2번 시나리오 3.5(주차·충전)는 최신 3.2로 이동했습니다.':'';current=data.cuts.find(c=>c.scenario===Number(p.get('scenario'))&&c.cut===p.get('cut'))||data.cuts.find(c=>c.scenario===Number(p.get('scenario')))||data.cuts[0];if(legacy||p.get('cut')!==current.cut||Number(p.get('scenario'))!==current.scenario)history.replaceState(null,'',`#scenario=${current.scenario}&cut=${current.cut}`);const a=data.cuts.filter(c=>c.scenario===current.scenario),i=a.indexOf(current);seconds=demo.cuts[current.id].entrySeconds;progress=0;playing=true;document.title=`${current.id} · OS UI 시뮬레이터`;$('#position').textContent=`시나리오 ${current.scenario} · 씬 ${current.scene} · 컷 ${current.cut} / ${i+1}번째 · ${a.length}컷`;$('#title').textContent=current.title;$('#scenarios').innerHTML=data.scenarios.map(s=>`<button data-scenario="${s.id}" class="${s.id===current.scenario?'active':''}"><b>${String(s.id).padStart(2,'0')}</b><span>${esc(s.title)}</span><small>${data.cuts.filter(c=>c.scenario===s.id).length}컷</small></button>`).join('');$('#cut-select').innerHTML=a.map(c=>`<option value="${c.id}" ${c.id===current.id?'selected':''}>${c.cut} · ${esc(c.title)}</option>`).join('');$('#prev').disabled=i===0;$('#next').disabled=i===a.length-1;$('#next-scenario').hidden=i!==a.length-1||current.scenario===4;$('#vo').textContent=current.vo.displayText||'V.O 원문 미기입';$('#vo-status').textContent=status(current.vo.status);$('#vo-directions').textContent=current.vo.directions.length?'효과음·발화 지시: '+current.vo.directions.join(' '):'';$('#total-count').textContent=`총 ${data.cuts.length}컷 · 16:9 · 모노톤 시연`; $('#duration').textContent=current.duration.sourceSeconds==null?`원문 길이 미정 / 연출 미리보기 ${duration()}초 / 상시 루프 ${demo.cuts[current.id].loopSeconds}초`:`원문 ${duration()}초 / 상시 루프 ${demo.cuts[current.id].loopSeconds}초`;$('#notes').textContent=demo.cuts[current.id].note;$('#cues').innerHTML=current.timeline.map((t,i)=>`<button data-cue="${t.atNormalized}"><small>0${i+1} · ${Math.round(t.atNormalized*100)}%</small>${esc(t.action)}</button>`).join('');view=mountScene($('#stage'),current,demo);$('#annotation-layer').hidden=!annotations;details();syncControls();draw();startClock();}
$('#scenarios').onclick=e=>{const b=e.target.closest('[data-scenario]');if(b)go(data.cuts.find(c=>c.scenario===Number(b.dataset.scenario)))};$('#cut-select').onchange=e=>go(data.cuts.find(c=>c.id===e.target.value));$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#next-scenario').onclick=()=>go(data.cuts.find(c=>c.scenario===current.scenario+1));
$('#play').onclick=()=>{playing=!playing;syncControls();startClock()};$('#reset').onclick=()=>{seconds=0;progress=0;playing=true;syncControls();draw();startClock()};$('#mode').onchange=()=>{seconds=demo.cuts[current.id].entrySeconds;progress=0;playing=true;if($('#mode').value==='sequence')$('#timing-review').open=true;syncControls();draw();startClock()};$('#seek').oninput=e=>{playing=false;progress=Number(e.target.value)/1000;seconds=progress*demo.cuts[current.id].loopSeconds;syncControls();draw();stopClock()};$('#cues').onclick=e=>{const b=e.target.closest('[data-cue]');if(b){progress=Number(b.dataset.cue);seconds=progress*demo.cuts[current.id].loopSeconds;playing=false;syncControls();draw();stopClock()}};
$('#annotations').onclick=()=>{annotations=!annotations;$('#annotation-layer').hidden=!annotations;$('#annotations').textContent=annotations?'주석 숨기기':'주석 보기';$('#annotations').setAttribute('aria-pressed',String(annotations))};$('#motion').onchange=()=>{syncControls();draw();startClock()};reduced.addEventListener('change',e=>{$('#motion').checked=e.matches;syncControls();draw();startClock()});
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);tell('현재 컷 URL을 복사했습니다.')}catch{tell('주소창의 현재 URL을 복사해 주세요.')}};
window.addEventListener('hashchange',load);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopClock();else startClock()});window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','SUMMARY'].includes(e.target.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.code==='Space'){e.preventDefault();$('#play').click()}});
try{[data,source,demo]=await Promise.all(['cuts','source-extract','display-demo'].map(async n=>{const r=await fetch(`./data/${n}.json`);if(!r.ok)throw Error(`${n}: ${r.status}`);return r.json()}));load();document.documentElement.dataset.ready='true'}catch(e){$('#title').textContent='데이터를 불러오지 못했습니다';tell(e.message);console.error(e)}
