import {esc,R,L,P,C,T,img,group,graphic,photo,cityMap,floorMap,pbv,tree,park,virtualStage,modules,lidar,powerUnit,powerGraph} from './graphics.js';
export {esc};
const style=b=>`left:${b[0]}%;top:${b[1]}%;width:${b[2]}%;height:${b[3]}%`;
function field(s){const p=s.split(' · ');if(p.length===1)return `<div class="copy">${esc(s)}</div>`;const label=p.shift(),value=p.join(' · '),numeric=/^[+]?\d/.test(value);return `<div class="field ${numeric?'numeric':''}"><span class="field-label">${esc(label)}</span><span class="field-value">${value.split(' / ').map(v=>{const m=v.match(/^([+]?\d[\d,.:%–/ ]*)(kW|MW|kWh|km|m|min|sec)$/);return `<span class="value-part">${m?`<strong>${esc(m[1].trim())}</strong><small>${m[2]}</small>`:esc(v)}</span>`}).join('<span class="field-divider"></span>')}</span></div>`}
const fields=(list,cls='')=>`<div class="fields ${cls}">${list.map(field).join('')}</div>`;
const card=(b,title,body,cls='')=>`<section class="scene-panel ${cls}" style="${style(b)}"><h2>${esc(title)}</h2>${body}</section>`;
const bare=(b,body,cls='')=>`<div class="scene-content ${cls}" style="${style(b)}">${body}</div>`;
const head=s=>bare([4,4,86,10],`<h2 class="scene-heading">${esc(s)}</h2>`,'stage-heading');
function s1(c,v,d){let o='',ui='',cp=v.displayCopy,idx=c.order-1;const energy=c.layout==='plaza_hud',file=d.assets.graphics[idx]?.[0]?.file;
if(energy){o+=(c.cut==='4.3.1'?`<g class="phase-early">${img(d.assets.graphics[9][0].file,25,125,970,690)}</g><g class="phase-late">${img(file,25,125,970,690)}</g>`:img(file,25,125,970,690))+R(25,125,970,690,'none','#555',18);ui+=head(cp[0]);
if(['4.2.2','4.3.1'].includes(c.cut)){ui+=bare([7,37,15,5],'ESS · +240 kW','network-label')+bare([44,37,16,5],'V2G · +180 kW','network-label')+bare([20,81,21,5],'Mobile unit · +200 kW','network-label');o+=T(390,480,'+620 kW',24);}
if(c.cut==='4.1.1')ui+=card([65,20,31,58],cp[0],`<div class="model-icon">${graphic(powerUnit())}</div>${fields(cp.slice(1))}`);
if(c.cut==='4.1.2'||c.cut==='4.3.1'){const balance=c.cut==='4.3.1';ui+=card([64,17,33,73],cp[0],fields(cp.slice(1,4),'metric-stack')+powerGraph(d,balance)+fields(cp.slice(4)),balance?'':'warning');o+=`<g data-motion="pulse">${C(520,420,120)}</g>`;}
if(c.cut==='4.1.3'){ui+=card([65,22,31,61],cp[0],fields(cp.slice(1),'metric-stack'));o+=[0,1,2].map(i=>`<circle cx="480" cy="410" r="${60+i*60}" fill="none" stroke="#ddd" data-motion="wave" data-offset="${i}"/>`).join('');}
if(c.cut==='4.2.1')ui+=card([65,16,31,75],cp[0],`<div class="equipment-graphic">${graphic(powerUnit())}</div><div class="hero-copy">${esc(cp[1])}</div>${fields(cp.slice(2))}`);
if(c.cut==='4.2.2'){ui+=card([62,16,35,76],cp[0],fields(cp.slice(1,4),'sources')+fields(cp.slice(4),'support-total'));o+=P('M300 260 L500 420 L780 235 M500 420 L680 675','stroke-width="4" stroke-dasharray="9 9" data-motion="flow"');}
}else{o+=img(file,0,65,1600,780)+P('M30 110 V35 H1570 V110 M30 770 V865 H1570 V770','stroke-width="2"')+P('M270 900 Q800 670 1330 900','fill="#202020" stroke="#888" stroke-width="3"');if(idx>=2&&idx<=4)o+=img(d.assets.graphics[idx][1].file,1230,115,280,280);o+=P('M800 735 L795 585 L803 450','stroke-width="4" stroke-dasharray="10 17" data-motion="flow"');
if(c.cut==='3.3.2')ui+=head('Destination · Reward Plaza')+card([4,19,34,36],'Arrival in',`<div class="hero-number">4 <small>min</small> 20 <small>sec</small></div>${fields(cp.slice(1,3))}`)+card([4,61,34,30],'Charging plan',fields(cp.slice(3),'metric-grid'));
else if(c.cut==='3.3.1')ui+=card([5,20,33,58],cp[0],`<div class="hero-number">${esc(cp[1])}</div><p class="support-copy">${esc(cp[2])}</p>${fields(cp.slice(3))}`);
else{ui+=card([5,25,37,46],cp[0],fields(cp.slice(1),'large-fields'));}
if(c.cut==='3.2.1'){ui+=bare([64,22,30,12],'<div class="map-tag">Reward Plaza R-04</div>');o+=C(1100,480,35,'data-motion="pulse"');}}ui+=`<div class="vehicle-speed" aria-label="Vehicle speed"><div class="speed-value" data-motion="speed">00</div><div class="speed-unit">km/h</div><div class="speed-state">${d.vehicleSpeed[c.id].some(n=>n>0)?'Auto':'Parked'}</div><div class="speed-track"><span data-motion="speed-bar"></span></div></div>`;return{o,ui}}
function s2(c,v,d){
 const cp=v.displayCopy,k=c.rendererKey,state=c.state,closing=k==='morning-start';let o=R(0,0,1600,900,'#111','#333');
 for(let i=0;i<45;i++)o+=L(i*40,0,i*40,900,'opacity=".08"')+L(0,i*40,1600,i*40,'opacity=".08"');
 const ghost=b=>bare(b,'','slot-outline');
 const charging='<div class="charging-bar"><span data-motion="charge"></span></div>';
 const mobilitySummary=()=>'<div class="service-history mobility-summary"><span>EV-12 · Parking complete</span><span>ACR · Charging in progress 42%</span><span>Ready by · 18:00</span></div>';
 let ui=card([36,4,28,91],'Work mirror',
 '<div class="mirror-image" data-motion="'+(k==='equipment-proposal'?'lift':'breath')+'">'+photo(k==='greeting'?'agent':'body')+'</div>'+
 (k==='condition-check'?'<div class="scan-band" data-motion="scan-dom"></div>':'')+
 (['equipment-proposal','equipment-request'].includes(k)?'<div class="waist-focus" data-motion="pulse-dom"></div>':'')+
 '<div class="mirror-caption">'+(k==='greeting'?'Agent V · Connected':'Agent V · Background mode')+'</div>',closing?'mirror-panel closing-mirror':'mirror-panel');
 if(k==='greeting')return{o,ui:ui+ghost([3,4,31,36])+ghost([3,43,31,52])+ghost([66,4,31,27])+ghost([66,34,31,61])};
 const tasks=['09:00 · Sample records','14:00 · Plant inspection','Afternoon location · Room '+state.afternoonRoom];
 let today=fields(tasks);if(k==='afternoon-location-change')today=fields(tasks.slice(0,2))+'<div class="location-change"><div class="phase-early">'+fields(['Afternoon location · Room A'])+'</div><div class="phase-late">'+fields(['Afternoon location · Room B'])+'</div></div>';
 if(k==='morning-records')today=fields([cp[1],cp[5],'Afternoon location · Room B']);if(closing)today=fields([cp[1],cp[3],'Afternoon · Inspection scheduled']);
 ui+=state.briefing?card([3,4,31,36],closing||k==='morning-records'?cp[0]:'Today’s tasks',today,closing?'closing-slot':''):ghost([3,4,31,36]);
 if(!state.briefing)ui+=ghost([3,43,31,52]);
 else if(k==='daily-briefing')ui+=card([3,43,31,52],'Plant sample',photo('plant','plant-image')+fields([cp[4]]));
 else if(k==='morning-records')ui+=card([3,43,31,52],'Sample records',photo('plant','plant-image')+fields(cp.slice(2,5),'compact-fields'));
 else{let map=floorMap(k==='delivery-booking',state.afternoonRoom==='B');if(k==='afternoon-location-change')map='<div class="route-swap"><div class="phase-early">'+floorMap(false,false)+'</div><div class="phase-late">'+floorMap(false,true)+'</div></div>';
 ui+=card([3,43,31,52],k==='afternoon-location-change'?cp[0]:'Afternoon workspace',map+fields(k==='afternoon-location-change'?cp.slice(1):['Afternoon location · Room B','Inspection · 14:00'],'compact-fields'),closing?'workspace-panel closing-slot':'workspace-panel');}
 if(k==='condition-check')ui+=card([66,4,31,31],cp[0],'<div class="choice-row">'+cp.slice(1,4).map((s,i)=>'<span class="choice '+(i===2?'chosen':'')+'">'+esc(s)+'</span>').join('')+'</div><div class="condition-result"><b>'+esc(cp[4])+'</b><span>'+esc(cp[5])+'</span></div>');
 else if(state.condition)ui+=card([66,4,31,24],'Condition','<div class="condition-result"><b>Take it easy</b><span>A little tired · Condition saved</span></div>',closing?'closing-slot':'');else ui+=ghost([66,4,31,27]);
 if(k==='parking-charging'){ui+=card([66,34,31,61],cp[0],photo('car','service-image')+fields(cp.slice(1))+'<div class="mobility-devices"><span>Parking Robot ✓</span><span>ACR ↗</span></div>'+charging,'service-panel');}
 else if(['condition-check','daily-briefing','afternoon-location-change'].includes(k)){ui+=ghost([66,37,31,30])+card([66,70,31,25],'Mobility status',mobilitySummary()+charging,'compact-mobility');}
 else{let asset=null,body=fields(cp.slice(1)),title=cp[0];if(k==='sample-received')asset='spot';if(k==='delivery-booking')asset='delivery';if(k==='equipment-proposal'){asset='xble';body=fields(cp.slice(1,4))+'<div class="choice-row"><span class="choice chosen">'+cp[4]+'</span><span class="choice">'+cp[5]+'</span></div><div class="lift-task">Sample case → Workbench</div>';}
 if(k==='equipment-request'){asset='xble';body=fields(cp.slice(1));}if(k==='morning-records'){title='Afternoon preparation';body=fields(['Inspection · 14:00 · Room B','Delivery · Scheduled','Equipment · Requested']);}if(closing)body=fields(['Delivery · Scheduled','Equipment · Requested','Next check · 13:45']);
 ui+=card([66,31,31,64],title,(asset?photo(asset,'service-image'):'')+(k==='sample-received'?photo('plant','received-sample'):'')+body+(state.delivery&&!['delivery-booking','workday-ready','morning-records','morning-start'].includes(k)?'<div class="carry-tag">Delivery · Scheduled</div>':'')+mobilitySummary()+charging,closing?'service-panel closing-slot':'service-panel');}
 if(c.scene>=4)o+=P('M600 882 H1000','data-motion="voice" stroke-width="2"');if(closing)ui+=bare([36,35,28,35],'<div class="os-mark">OS</div><div class="logo-caption">Agent V · Background mode</div>','phase-late ending-logo');return{o,ui};}
function s3(c,v){let o=park(),ui='',cp=v.displayCopy;if(['4.1','4.2','4.3'].includes(c.cut))o+=`<g class="${c.cut==='4.3'?'phase-early':''}">${virtualStage()}</g>`;if(['4.3','4.4','5.1','5.2'].includes(c.cut))o+=`<g class="${c.cut==='4.3'?'phase-late':''}">${tree(630,570,.6)}${tree(950,540,.55)}${P('M680 810 Q1030 610 880 500','stroke-dasharray="8 9" stroke-width="3" data-motion="flow"')}${R(485,610,175,48,'#333','#888',20)}</g>`;
if(['3.1','5.1','5.2'].includes(c.cut))o+=group(c.cut==='3.1'?710:790,310,770,465,pbv());if(c.cut==='5.3'){o=R(0,0,1600,900,'#171717','#555')+R(150,80,1300,630,'#2a2a2a','#777',130)+R(220,140,1160,460,'#141414','#999',90)+P('M220 510 L680 270 H970 L1380 510','stroke-width="2"')+P('M720 590 L780 280 M940 590 L900 280','stroke="#777"')+R(75,670,405,220,'#333','#999',80)+R(1120,670,405,220,'#333','#999',80)+R(690,740,220,110,'#333','#888',24);ui+=card([5,13,37,40],cp[0],`<div class="hero-number">${esc(cp[1])}</div>`,'phase-early')+card([5,13,38,53],cp[2],`<div class="hero-copy">${esc(cp[3])}</div>${fields(cp.slice(4))}`,'phase-late')+bare([57,45,36,39],graphic(cityMap(false,'PBV-07','Home')),'phase-late');}
else if(c.cut==='4.2'){ui+=card([65,14,31,48],cp[0],fields(cp.slice(1,3))+`<div class="action-copy">${esc(cp[3])}</div>`);o+=P('M220 790 H600','data-motion="voice" stroke-width="2"');}else{ui+=card([4,10,c.cut==='5.2'?40:36,cp.length>3?42:34],cp[0],fields(cp.slice(1),'large-fields'),'floating-panel');if(c.cut==='4.3')ui+=bare([68,8,25,10],'<div class="map-tag phase-early">Activity</div><div class="map-tag phase-late">Quiet</div>');}return{o,ui}}
function mix(label,values){return `<div class="mix-chart"><h3>${esc(label.split(' · ')[0])}</h3><div class="mix-bars">${values.map((n,i)=>`<div style="width:${n}%"><b>${n}</b><span>${['Cafe','Exhibition','Lounge'][i]}</span></div>`).join('')}</div></div>`}
function s4(c,v,d){let o=R(0,0,1600,900,'#111','#444')+group(30,95,1540,750,cityMap()),ui='',cp=v.displayCopy;ui+=head(({'3.1':'LM-01 · Operation overview','4.4':'Overnight relocation','4.5':'Relocation plan','4.3':'Asset dispatch'})[c.cut]||cp[0]);
if(c.cut==='3.1'){o=R(0,0,1600,900,'#111','#333')+group(30,350,1540,530,modules());ui+=bare([4,17,92,32],`<div class="overview-metrics">${cp.slice(0,5).map(s=>`<div class="metric-cell">${field(s)}</div>`).join('')}</div>`)+card([65,54,31,32],'Service status',fields(cp.slice(5,8)),'service-status')+bare([4,88,80,7],`<div class="scene-sub">${esc(cp[8])}</div>`);}
if(c.cut==='3.2')ui+=bare([4,24,92,59],`<div class="candidate-grid">${cp.slice(1).map((s,i)=>`<section><span class="candidate-code">0${i+1}</span><h3>${esc(s)}</h3>${graphic(i===0?P('M70 400 H930 M200 100 V520 M450 100 V520 M700 100 V520','stroke-width="16"'):i===1?modules():P('M200 400 V170 L500 70 L800 170 V400Z M200 400 H800 M280 200 V380 M430 170 V380 M580 170 V380 M720 200 V380','stroke-width="12"'))}${fields(d.candidateDetails[i])}</section>`).join('')}</div>`);
if(c.cut==='3.3')ui+=card([4,19,58,65],cp[0],mix(cp[2],[40,35,25])+mix(cp[3],[20,55,25]))+card([66,26,30,48],'Culture District',`<div class="site-symbol">${graphic(modules())}</div>${fields([cp[1]])}`);
if(c.cut==='4.1'){o=R(0,0,1600,900,'#111','#333')+group(30,220,900,540,modules());ui+=card([61,18,35,70],cp[0],fields(cp.slice(1),'inventory-fields'));}
if(c.cut==='4.2'){o=R(0,0,1600,900,'#111','#333')+group(40,160,930,570,lidar())+group(995,190,560,430,cityMap(true));ui+=bare([5,79,55,16],`${photo('spot','spot-survey')}<div>${fields([cp[3],cp[4]],'horizontal')}</div>`,'survey-checks')+card([65,68,31,27],'Route survey',fields(cp.slice(1,3)));}
if(c.cut==='4.3'){ui+=card([3,20,29,68],'Asset queue',fields(cp.slice(0,3),'queue-fields')+photo('plant','queue-asset'))+card([69,20,28,68],'Route assignment',photo('spot','service-image')+fields(cp.slice(3)));o+=P('M500 580 L680 430 L1030 430 M680 430 V280 H1030','stroke-width="4" data-motion="flow" stroke-dasharray="10 9"');}
if(c.cut==='4.4')ui+=card([4,18,40,51],'Infrastructure',fields(cp.slice(0,3)))+card([55,18,41,51],'City review',fields(cp.slice(3)))+bare([4,74,92,22],`<div class="transport-timeline">${d.transport.map(([day,t,label])=>`<div><small>${day}</small><strong>${t}</strong><span>${label}</span></div>`).join('')}</div>`);
if(c.cut==='4.5')ui+=bare([5,22,51,60],`<div class="process-flow">${cp[0].split(' → ').map((s,i)=>`<div><span>0${i+1}</span><b>${s}</b></div>`).join('')}</div>`)+card([61,19,35,65],'Plan status',fields(cp.slice(1,5))+`<div class="action-copy">${esc(cp[5])}</div>`);
if(c.cut==='5.1')ui+=card([5,21,39,64],cp[0],fields(cp.slice(1,5),'large-fields'))+card([61,29,35,52],'Tomorrow',fields(cp.slice(5)));
if(c.cut==='5.2')ui+=card([5,23,38,54],'Tomorrow',fields(cp.slice(0,2))+`<p class="route-copy">${esc(cp[2])}</p>`)+card([63,24,33,51],'New site preview',fields(cp.slice(3,5),'large-fields'))+bare([7,84,86,12],`<div class="end-line"><strong>${esc(cp[5])}</strong><span>${esc(cp[6])}</span></div>`);return{o,ui}}
export function mountScene(stage,c,d){const v=d.cuts[c.id],r=[null,s1,s2,s3,s4][c.scenario](c,v,d);r.o+=C(1542,45,5,'data-motion="pulse"');stage.dataset.cut=c.id;stage.querySelector('#scene').innerHTML=r.o;stage.querySelector('#ui-layer').innerHTML=r.ui;const panels=[...stage.querySelectorAll('.scene-panel,.scene-content')];stage.querySelector('#annotation-layer').innerHTML=panels.map((p,i)=>`<div class="annotation" style="${p.getAttribute('style')}"><b>${String(i+1).padStart(2,'0')}</b></div>`).join('');const animated=[...stage.querySelectorAll('[data-motion]')];let lastPhase='',lastCue=-1;
return{captions:panels.map((p,i)=>({index:i+1,title:p.querySelector('h2,h3')?.textContent||'화면 요소',bounds:p.getAttribute('style'),copy:(()=>{const w=document.createTreeWalker(p,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode()){const t=w.currentNode.textContent.trim();if(t)a.push(t)}return a.join(' / ')})()})),update(seconds,{reduced=false,mode='always',progress=0}={}){const t=reduced?4:seconds%v.loopSeconds,phase=reduced?'late':mode==='sequence'?(progress<(c.id==='S2-5.3'?.7:.35)?'early':'late'):t<v.transitionAt?'early':'late';if(phase!==lastPhase){stage.dataset.phase=phase;lastPhase=phase}const cue=mode==='sequence'?(progress<.35?0:progress<.7?1:2):2;if(cue!==lastCue){stage.dataset.cue=String(cue);lastCue=cue}for(let i=0;i<panels.length;i++){const show=mode!=='sequence'||progress>=(v.sequenceReveal[i]??0);panels[i].style.visibility=show?'visible':'hidden'}stage.classList.toggle('ending',c.id==='S2-5.3'&&phase==='late');stage.dataset.loopTime=t.toFixed(2);if(c.id==='S2-5.3'){const elapsed=mode==='sequence'?(progress-.7)*v.loopSeconds:t-v.transitionAt;const fade=phase==='early'?0:reduced?1:Math.min(1,Math.max(0,elapsed/.8));for(const panel of panels){if(panel.classList.contains('closing-slot')){panel.style.opacity=String(1-fade);panel.style.transform='scale('+(1-.22*fade)+')'}if(panel.classList.contains('closing-mirror')){panel.style.opacity=String(1-.95*fade);panel.style.transform='rotate('+(2*fade)+'deg) scale('+(1-.06*fade)+')'}}}
for(const el of animated){const p=reduced?1:(seconds%4)/4;switch(el.dataset.motion){case'speed':case'speed-bar':{const keys=d.vehicleSpeed[c.id],q=(reduced?0:(seconds%v.loopSeconds)/v.loopSeconds)*(keys.length-1),k=Math.min(keys.length-2,Math.floor(q)),f=q-k,e=f*f*(3-2*f),speed=keys[k]+(keys[k+1]-keys[k])*e;if(el.dataset.motion==='speed'){const value=String(Math.round(speed)).padStart(2,'0');if(el.textContent!==value)el.textContent=value}else el.style.transform=`scaleX(${speed/60})`;break}case'charge':el.style.backgroundPosition=`${p*100}% 0`;break;case'flow':el.setAttribute('stroke-dashoffset',String(-p*64));break;case'pulse':el.setAttribute('opacity',String(reduced?.85:.6+.35*Math.sin(p*Math.PI*2)**2));break;case'wave':{const q=reduced?.65:(p+Number(el.dataset.offset)/3)%1;el.setAttribute('r',String(50+q*220));el.setAttribute('opacity',String(1-q));break}case'lift':el.style.transform=`translateY(${reduced?0:Math.sin(p*Math.PI*2)*1.5}%) rotate(${reduced?0:Math.sin(p*Math.PI*2)*3}deg)`;break;case'breath':el.style.transform=`scale(${reduced?1:1+Math.sin(p*Math.PI*2)*.008})`;break;case'float':el.setAttribute('transform',`translate(0 ${reduced?0:Math.sin(p*Math.PI*2)*2})`);break;case'scan':el.setAttribute('transform',`translate(0 ${reduced?0:(p-.5)*210})`);break;case'scan-dom':el.style.top=`${reduced?48:15+p*66}%`;break;case'pulse-dom':el.style.opacity=String(reduced?.9:.6+.4*Math.sin(p*Math.PI*2)**2);break;case'voice':{const x=c.scenario===2?600:220,y=c.scenario===2?882:790;let points='';for(let i=0;i<60;i++)points+=`${i?'L':'M'}${x+i*6.6} ${y+Math.sin(i*.8+p*10)*12*Math.sin(i/59*Math.PI)} `;el.setAttribute('d',points);break}case'survey':{const points=[[150,495],[470,495],[470,255],[790,255],[790,125]],q=(reduced?.8:p)*4,k=Math.min(3,Math.floor(q)),f=q-k;el.setAttribute('transform',`translate(${points[k][0]+(points[k+1][0]-points[k][0])*f} ${points[k][1]+(points[k+1][1]-points[k][1])*f})`);break}}}}}}



